"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const expressionUtils_1 = require("./expressionUtils");
exports.expressions = [
    // invalid
    ['', undefined],
    ['a', undefined],
    ['123', undefined],
    [':::', undefined],
    ['XDK', undefined],
    ['fooXD', undefined],
    [':) hey', undefined],
    ['тот', undefined],
    // in text
    [' :) ', [1 /* Neutral */, 1 /* Neutral */, 0 /* Smile */]],
    ['hi :)', [1 /* Neutral */, 1 /* Neutral */, 0 /* Smile */]],
    // horizontal (right)
    [':-)', [1 /* Neutral */, 1 /* Neutral */, 0 /* Smile */]],
    [':)', [1 /* Neutral */, 1 /* Neutral */, 0 /* Smile */]],
    ['=)', [1 /* Neutral */, 1 /* Neutral */, 0 /* Smile */]],
    [':]', [1 /* Neutral */, 1 /* Neutral */, 0 /* Smile */]],
    [':>', [1 /* Neutral */, 1 /* Neutral */, 0 /* Smile */]],
    [':}', [1 /* Neutral */, 1 /* Neutral */, 0 /* Smile */]],
    [':3', [1 /* Neutral */, 1 /* Neutral */, 0 /* Smile */]],
    ['rus :з', [1 /* Neutral */, 1 /* Neutral */, 0 /* Smile */]],
    ['rus :э', [1 /* Neutral */, 1 /* Neutral */, 0 /* Smile */]],
    [':(', [15 /* Sad */, 15 /* Sad */, 1 /* Frown */]],
    [':[', [15 /* Sad */, 15 /* Sad */, 1 /* Frown */]],
    [':C', [15 /* Sad */, 15 /* Sad */, 1 /* Frown */]],
    [':c', [15 /* Sad */, 15 /* Sad */, 1 /* Frown */]],
    ['rus :С', [15 /* Sad */, 15 /* Sad */, 1 /* Frown */]],
    ['rus :с', [15 /* Sad */, 15 /* Sad */, 1 /* Frown */]],
    [':<', [15 /* Sad */, 15 /* Sad */, 1 /* Frown */]],
    [':{', [15 /* Sad */, 15 /* Sad */, 1 /* Frown */]],
    [':I', [1 /* Neutral */, 1 /* Neutral */, 3 /* Scrunch */]],
    [':t', [1 /* Neutral */, 1 /* Neutral */, 3 /* Scrunch */]],
    [':T', [1 /* Neutral */, 1 /* Neutral */, 3 /* Scrunch */]],
    ['rus :Т', [1 /* Neutral */, 1 /* Neutral */, 3 /* Scrunch */]],
    ['rus :т', [1 /* Neutral */, 1 /* Neutral */, 3 /* Scrunch */]],
    [':P', [1 /* Neutral */, 1 /* Neutral */, 4 /* Blep */]],
    [':p', [1 /* Neutral */, 1 /* Neutral */, 4 /* Blep */]],
    [':d', [1 /* Neutral */, 1 /* Neutral */, 4 /* Blep */]],
    [':b', [1 /* Neutral */, 1 /* Neutral */, 25 /* FlatBlep */]],
    ['rus :Р', [1 /* Neutral */, 1 /* Neutral */, 4 /* Blep */]],
    ['rus :р', [1 /* Neutral */, 1 /* Neutral */, 4 /* Blep */]],
    [':D', [1 /* Neutral */, 1 /* Neutral */, 5 /* SmileOpen */]],
    [':DD', [1 /* Neutral */, 1 /* Neutral */, 9 /* SmileOpen2 */]],
    [':DDD', [1 /* Neutral */, 1 /* Neutral */, 14 /* SmileOpen3 */]],
    [':DDDDD', [1 /* Neutral */, 1 /* Neutral */, 14 /* SmileOpen3 */]],
    [':O', [1 /* Neutral */, 1 /* Neutral */, 12 /* ConcernedOpen2 */]],
    [':0', [1 /* Neutral */, 1 /* Neutral */, 8 /* ConcernedOpen */]],
    [':o', [1 /* Neutral */, 1 /* Neutral */, 24 /* Oh */]],
    [':|', [1 /* Neutral */, 1 /* Neutral */, 6 /* Flat */]],
    [':l', [1 /* Neutral */, 1 /* Neutral */, 6 /* Flat */]],
    [':i', [1 /* Neutral */, 1 /* Neutral */, 6 /* Flat */]],
    [':v', [1 /* Neutral */, 1 /* Neutral */, 8 /* ConcernedOpen */]],
    [':V', [1 /* Neutral */, 1 /* Neutral */, 10 /* FrownOpen */]],
    [':u', [1 /* Neutral */, 1 /* Neutral */, 11 /* NeutralOpen2 */]],
    [':n', [1 /* Neutral */, 1 /* Neutral */, 11 /* NeutralOpen2 */]],
    [':U', [1 /* Neutral */, 1 /* Neutral */, 15 /* NeutralOpen3 */]],
    [':*', [1 /* Neutral */, 1 /* Neutral */, 13 /* Kiss */]],
    [':x', [1 /* Neutral */, 1 /* Neutral */, 13 /* Kiss */]],
    [':X', [1 /* Neutral */, 1 /* Neutral */, 13 /* Kiss */]],
    [':/', [1 /* Neutral */, 1 /* Neutral */, 7 /* Concerned */]],
    [':\\', [1 /* Neutral */, 1 /* Neutral */, 7 /* Concerned */]],
    [':S', [1 /* Neutral */, 1 /* Neutral */, 7 /* Concerned */]],
    [':s', [1 /* Neutral */, 1 /* Neutral */, 7 /* Concerned */]],
    [':?', [1 /* Neutral */, 1 /* Neutral */, 7 /* Concerned */]],
    ['>:(', [19 /* Angry */, 19 /* Angry */, 1 /* Frown */]],
    ['>:<', [19 /* Angry */, 19 /* Angry */, 1 /* Frown */]],
    ['<:>', [15 /* Sad */, 15 /* Sad */, 0 /* Smile */]],
    ['XD', [23 /* X */, 23 /* X */, 5 /* SmileOpen */]],
    ['xD', [23 /* X */, 23 /* X */, 5 /* SmileOpen */]],
    [':L', [1 /* Neutral */, 1 /* Neutral */, 23 /* NeutralPant */]],
    [':Q', [1 /* Neutral */, 1 /* Neutral */, 22 /* SmilePant */]],
    ['B)', [3 /* Neutral3 */, 3 /* Neutral3 */, 0 /* Smile */]],
    ['8)', [1 /* Neutral */, 1 /* Neutral */, 0 /* Smile */, 6 /* Shocked */, 6 /* Shocked */]],
    ['>8)', [19 /* Angry */, 19 /* Angry */, 0 /* Smile */, 6 /* Shocked */, 6 /* Shocked */]],
    ['<:)', [15 /* Sad */, 15 /* Sad */, 0 /* Smile */]],
    ['>B)', [20 /* Angry2 */, 20 /* Angry2 */, 0 /* Smile */]],
    ['<B)', [16 /* Sad2 */, 16 /* Sad2 */, 0 /* Smile */]],
    ['|:)', [7 /* Frown */, 7 /* Frown */, 0 /* Smile */]],
    ['|B)', [8 /* Frown2 */, 8 /* Frown2 */, 0 /* Smile */]],
    ['|)', [11 /* Lines */, 11 /* Lines */, 0 /* Smile */]],
    [':))', [1 /* Neutral */, 1 /* Neutral */, 18 /* SmileTeeth */]],
    [':]]', [1 /* Neutral */, 1 /* Neutral */, 18 /* SmileTeeth */]],
    [':||', [1 /* Neutral */, 1 /* Neutral */, 20 /* NeutralTeeth */]],
    [':((', [1 /* Neutral */, 1 /* Neutral */, 19 /* FrownTeeth */]],
    [':[[', [1 /* Neutral */, 1 /* Neutral */, 19 /* FrownTeeth */]],
    ['://', [1 /* Neutral */, 1 /* Neutral */, 21 /* ConcernedTeeth */]],
    [':SS', [1 /* Neutral */, 1 /* Neutral */, 21 /* ConcernedTeeth */]],
    [';)', [6 /* Closed */, 1 /* Neutral */, 0 /* Smile */]],
    [';(', [16 /* Sad2 */, 16 /* Sad2 */, 1 /* Frown */, 0 /* Forward */, 0 /* Forward */, 8 /* Tears */]],
    ['>;(', [19 /* Angry */, 19 /* Angry */, 1 /* Frown */, 0 /* Forward */, 0 /* Forward */, 8 /* Tears */]],
    ['%)', [1 /* Neutral */, 1 /* Neutral */, 0 /* Smile */, 0 /* Forward */, 1 /* Up */]],
    [`c':`, [1 /* Neutral */, 1 /* Neutral */, 0 /* Smile */, 0 /* Forward */, 0 /* Forward */, 8 /* Tears */]],
    [`:')`, [1 /* Neutral */, 1 /* Neutral */, 0 /* Smile */, 0 /* Forward */, 0 /* Forward */, 8 /* Tears */]],
    [`:'(`, [15 /* Sad */, 15 /* Sad */, 1 /* Frown */, 0 /* Forward */, 0 /* Forward */, 8 /* Tears */]],
    [`=,)`, [1 /* Neutral */, 1 /* Neutral */, 0 /* Smile */, 0 /* Forward */, 0 /* Forward */, 8 /* Tears */]],
    ['=`)', [1 /* Neutral */, 1 /* Neutral */, 0 /* Smile */, 0 /* Forward */, 0 /* Forward */, 8 /* Tears */]],
    // TODO: :@ :y :'9
    // horizontal (left)
    ['(-:', [1 /* Neutral */, 1 /* Neutral */, 0 /* Smile */]],
    ['|:', [1 /* Neutral */, 1 /* Neutral */, 6 /* Flat */]],
    ['(:', [1 /* Neutral */, 1 /* Neutral */, 0 /* Smile */]],
    ['[:', [1 /* Neutral */, 1 /* Neutral */, 0 /* Smile */]],
    ['c:', [1 /* Neutral */, 1 /* Neutral */, 0 /* Smile */]],
    ['C:', [1 /* Neutral */, 1 /* Neutral */, 0 /* Smile */]],
    ['rus с:', [1 /* Neutral */, 1 /* Neutral */, 0 /* Smile */]],
    ['rus С:', [1 /* Neutral */, 1 /* Neutral */, 0 /* Smile */]],
    ['):', [15 /* Sad */, 15 /* Sad */, 1 /* Frown */]],
    ['D:', [15 /* Sad */, 15 /* Sad */, 12 /* ConcernedOpen2 */]],
    ['DD:', [15 /* Sad */, 15 /* Sad */, 16 /* ConcernedOpen3 */]],
    ['DDDDD:', [15 /* Sad */, 15 /* Sad */, 16 /* ConcernedOpen3 */]],
    ['D:<', [19 /* Angry */, 19 /* Angry */, 12 /* ConcernedOpen2 */]],
    ['D8<', [19 /* Angry */, 19 /* Angry */, 12 /* ConcernedOpen2 */, 6 /* Shocked */, 6 /* Shocked */]],
    ['):<', [19 /* Angry */, 19 /* Angry */, 1 /* Frown */]],
    ['v:', [1 /* Neutral */, 1 /* Neutral */, 8 /* ConcernedOpen */]],
    ['/:', [1 /* Neutral */, 1 /* Neutral */, 7 /* Concerned */]],
    ['(:>', [15 /* Sad */, 15 /* Sad */, 0 /* Smile */]],
    ['(:|', [7 /* Frown */, 7 /* Frown */, 0 /* Smile */]],
    ['(|', [11 /* Lines */, 11 /* Lines */, 0 /* Smile */]],
    ['((:', [1 /* Neutral */, 1 /* Neutral */, 18 /* SmileTeeth */]],
    ['[[:', [1 /* Neutral */, 1 /* Neutral */, 18 /* SmileTeeth */]],
    ['||:', [1 /* Neutral */, 1 /* Neutral */, 20 /* NeutralTeeth */]],
    [')):', [1 /* Neutral */, 1 /* Neutral */, 19 /* FrownTeeth */]],
    ['(;', [1 /* Neutral */, 6 /* Closed */, 0 /* Smile */]],
    // horizontal (invalid)
    ['||', undefined],
    ['|||', undefined],
    ['>||', undefined],
    ['>xD', undefined],
    ['(X<', undefined],
    ['x-x', undefined],
    // vertical
    ['-_-', [8 /* Frown2 */, 8 /* Frown2 */, 6 /* Flat */]],
    ['-.-', [8 /* Frown2 */, 8 /* Frown2 */, 13 /* Kiss */]],
    ['-,-', [8 /* Frown2 */, 8 /* Frown2 */, 13 /* Kiss */]],
    ['^_^', [13 /* ClosedHappy2 */, 13 /* ClosedHappy2 */, 6 /* Flat */]],
    ['-_^', [6 /* Closed */, 13 /* ClosedHappy2 */, 6 /* Flat */]],
    ['o_O', [2 /* Neutral2 */, 1 /* Neutral */, 6 /* Flat */]],
    ['0_o', [1 /* Neutral */, 2 /* Neutral2 */, 6 /* Flat */]],
    ['o_o', [1 /* Neutral */, 1 /* Neutral */, 6 /* Flat */]],
    ['o,o', [1 /* Neutral */, 1 /* Neutral */, 13 /* Kiss */]],
    ['ono', [1 /* Neutral */, 1 /* Neutral */, 1 /* Frown */]],
    ['O_O', [1 /* Neutral */, 1 /* Neutral */, 6 /* Flat */, 6 /* Shocked */, 6 /* Shocked */]],
    ['OoO', [1 /* Neutral */, 1 /* Neutral */, 8 /* ConcernedOpen */, 6 /* Shocked */, 6 /* Shocked */]],
    ['0_0', [1 /* Neutral */, 1 /* Neutral */, 6 /* Flat */]],
    ['°_°', [1 /* Neutral */, 1 /* Neutral */, 6 /* Flat */]],
    ['0.0', [1 /* Neutral */, 1 /* Neutral */, 13 /* Kiss */]],
    ['._.', [1 /* Neutral */, 1 /* Neutral */, 6 /* Flat */]],
    [',_,', [15 /* Sad */, 15 /* Sad */, 6 /* Flat */]],
    ['v_V', [6 /* Closed */, 6 /* Closed */, 6 /* Flat */]],
    ['u_U', [6 /* Closed */, 6 /* Closed */, 6 /* Flat */]],
    ['n_n', [14 /* ClosedHappy */, 14 /* ClosedHappy */, 6 /* Flat */]],
    ['>_<', [23 /* X */, 23 /* X */, 6 /* Flat */, 2 /* Left */, 3 /* Right */]],
    ['>c<', [23 /* X */, 23 /* X */, 0 /* Smile */, 2 /* Left */, 3 /* Right */]],
    [`'c'`, [1 /* Neutral */, 1 /* Neutral */, 0 /* Smile */]],
    ['-C-', [6 /* Closed */, 6 /* Closed */, 0 /* Smile */]],
    ['rus -с-', [6 /* Closed */, 6 /* Closed */, 0 /* Smile */]],
    ['-v-', [6 /* Closed */, 6 /* Closed */, 0 /* Smile */]],
    ['-V-', [6 /* Closed */, 6 /* Closed */, 0 /* Smile */]],
    ['-U-', [6 /* Closed */, 6 /* Closed */, 0 /* Smile */]],
    ['-u-', [6 /* Closed */, 6 /* Closed */, 0 /* Smile */]],
    ['-w-', [6 /* Closed */, 6 /* Closed */, 0 /* Smile */]],
    ['-W-', [6 /* Closed */, 6 /* Closed */, 0 /* Smile */]],
    [`-👃-`, [6 /* Closed */, 6 /* Closed */, 0 /* Smile */]],
    [`'_'`, [1 /* Neutral */, 1 /* Neutral */, 6 /* Flat */]],
    [`-*-`, [6 /* Closed */, 6 /* Closed */, 13 /* Kiss */]],
    [`-x-`, [6 /* Closed */, 6 /* Closed */, 13 /* Kiss */]],
    [`-X-`, [6 /* Closed */, 6 /* Closed */, 13 /* Kiss */]],
    [`>x<`, [23 /* X */, 23 /* X */, 13 /* Kiss */, 2 /* Left */, 3 /* Right */]],
    [`-o-`, [6 /* Closed */, 6 /* Closed */, 8 /* ConcernedOpen */]],
    [`-O-`, [6 /* Closed */, 6 /* Closed */, 12 /* ConcernedOpen2 */]],
    [`-0-`, [6 /* Closed */, 6 /* Closed */, 12 /* ConcernedOpen2 */]],
    [`^o^`, [13 /* ClosedHappy2 */, 13 /* ClosedHappy2 */, 9 /* SmileOpen2 */]],
    [`^O^`, [13 /* ClosedHappy2 */, 13 /* ClosedHappy2 */, 14 /* SmileOpen3 */]],
    [`-n-`, [6 /* Closed */, 6 /* Closed */, 1 /* Frown */]],
    [`-m-`, [6 /* Closed */, 6 /* Closed */, 1 /* Frown */]],
    [`-^-`, [6 /* Closed */, 6 /* Closed */, 1 /* Frown */]],
    [`-~-`, [6 /* Closed */, 6 /* Closed */, 7 /* Concerned */]],
    [`-3-`, [6 /* Closed */, 6 /* Closed */, 13 /* Kiss */]],
    [`rus -з-`, [6 /* Closed */, 6 /* Closed */, 13 /* Kiss */]],
    [`rus -э-`, [6 /* Closed */, 6 /* Closed */, 13 /* Kiss */]],
    [`-q-`, [6 /* Closed */, 6 /* Closed */, 23 /* NeutralPant */]],
    [`-p-`, [6 /* Closed */, 6 /* Closed */, 23 /* NeutralPant */]],
    [`-P-`, [6 /* Closed */, 6 /* Closed */, 22 /* SmilePant */]],
    [`-Q-`, [6 /* Closed */, 6 /* Closed */, 22 /* SmilePant */]],
    [`-A-`, [6 /* Closed */, 6 /* Closed */, 12 /* ConcernedOpen2 */]],
    [`q-q`, [15 /* Sad */, 15 /* Sad */, 2 /* Neutral */, 0 /* Forward */, 0 /* Forward */, 4 /* Cry */]],
    [`p-p`, [15 /* Sad */, 15 /* Sad */, 2 /* Neutral */, 0 /* Forward */, 0 /* Forward */, 4 /* Cry */]],
    [`p-q`, [15 /* Sad */, 15 /* Sad */, 2 /* Neutral */, 0 /* Forward */, 0 /* Forward */, 4 /* Cry */]],
    [`rus р-р`, [15 /* Sad */, 15 /* Sad */, 2 /* Neutral */, 0 /* Forward */, 0 /* Forward */, 4 /* Cry */]],
    [`;-;`, [15 /* Sad */, 15 /* Sad */, 2 /* Neutral */, 0 /* Forward */, 0 /* Forward */, 4 /* Cry */]],
    [`:-:`, [15 /* Sad */, 15 /* Sad */, 2 /* Neutral */]],
    [`P-P`, [15 /* Sad */, 15 /* Sad */, 2 /* Neutral */, 0 /* Forward */, 0 /* Forward */, 4 /* Cry */]],
    [`rus Р-Р`, [15 /* Sad */, 15 /* Sad */, 2 /* Neutral */, 0 /* Forward */, 0 /* Forward */, 4 /* Cry */]],
    [`t-t`, [21 /* Peaceful */, 21 /* Peaceful */, 2 /* Neutral */]],
    [`Т_Т`, [21 /* Peaceful */, 21 /* Peaceful */, 6 /* Flat */, 0 /* Forward */, 0 /* Forward */, 4 /* Cry */]],
    [`rus Т_т`, [21 /* Peaceful */, 21 /* Peaceful */, 6 /* Flat */, 0 /* Forward */, 0 /* Forward */, 4 /* Cry */]],
    [`Q-Q`, [15 /* Sad */, 15 /* Sad */, 2 /* Neutral */, 6 /* Shocked */, 6 /* Shocked */, 4 /* Cry */]],
    [`y-y`, [6 /* Closed */, 6 /* Closed */, 2 /* Neutral */, 0 /* Forward */, 0 /* Forward */, 4 /* Cry */]],
    [`Y-Y`, [6 /* Closed */, 6 /* Closed */, 2 /* Neutral */, 0 /* Forward */, 0 /* Forward */, 4 /* Cry */]],
    [`у-у`, [6 /* Closed */, 6 /* Closed */, 2 /* Neutral */, 0 /* Forward */, 0 /* Forward */, 4 /* Cry */]],
    [`У-У`, [6 /* Closed */, 6 /* Closed */, 2 /* Neutral */, 0 /* Forward */, 0 /* Forward */, 4 /* Cry */]],
    [`ò_ó`, [19 /* Angry */, 19 /* Angry */, 6 /* Flat */]],
    [`ó_ò`, [15 /* Sad */, 15 /* Sad */, 6 /* Flat */]],
    [`ô_ô`, [7 /* Frown */, 7 /* Frown */, 6 /* Flat */]],
    [`õ_õ`, [7 /* Frown */, 7 /* Frown */, 6 /* Flat */]],
    [`ō_ō`, [7 /* Frown */, 7 /* Frown */, 6 /* Flat */]],
    [`ŏ_ŏ`, [7 /* Frown */, 7 /* Frown */, 6 /* Flat */]],
    [`Ò_Ó`, [19 /* Angry */, 19 /* Angry */, 6 /* Flat */, 6 /* Shocked */, 6 /* Shocked */]],
    [`Ô_Ô`, [7 /* Frown */, 7 /* Frown */, 6 /* Flat */, 6 /* Shocked */, 6 /* Shocked */]],
    [`Õ_Õ`, [7 /* Frown */, 7 /* Frown */, 6 /* Flat */, 6 /* Shocked */, 6 /* Shocked */]],
    [`Ō_Ō`, [7 /* Frown */, 7 /* Frown */, 6 /* Flat */, 6 /* Shocked */, 6 /* Shocked */]],
    [`Ŏ_Ŏ`, [7 /* Frown */, 7 /* Frown */, 6 /* Flat */, 6 /* Shocked */, 6 /* Shocked */]],
    [`=_=`, [4 /* Neutral4 */, 4 /* Neutral4 */, 6 /* Flat */]],
    [`a_a`, [8 /* Frown2 */, 8 /* Frown2 */, 6 /* Flat */]],
    [`e_e`, [1 /* Neutral */, 1 /* Neutral */, 6 /* Flat */, 4 /* UpLeft */, 4 /* UpLeft */]],
    [`е_е`, [1 /* Neutral */, 1 /* Neutral */, 6 /* Flat */, 4 /* UpLeft */, 4 /* UpLeft */]],
    [`g_g`, [1 /* Neutral */, 1 /* Neutral */, 6 /* Flat */, 5 /* UpRight */, 5 /* UpRight */]],
    [`9_9`, [1 /* Neutral */, 1 /* Neutral */, 6 /* Flat */, 1 /* Up */, 1 /* Up */]],
    [`6_9`, [1 /* Neutral */, 1 /* Neutral */, 6 /* Flat */, 0 /* Forward */, 1 /* Up */]],
    ['>_>', [2 /* Neutral2 */, 2 /* Neutral2 */, 6 /* Flat */, 2 /* Left */, 2 /* Left */]],
    ['<_<', [2 /* Neutral2 */, 2 /* Neutral2 */, 6 /* Flat */, 3 /* Right */, 3 /* Right */]],
    ['<_>', [2 /* Neutral2 */, 2 /* Neutral2 */, 6 /* Flat */, 3 /* Right */, 2 /* Left */]],
    ['d_d', [1 /* Neutral */, 1 /* Neutral */, 6 /* Flat */, 3 /* Right */, 3 /* Right */]],
    ['b_b', [1 /* Neutral */, 1 /* Neutral */, 6 /* Flat */, 2 /* Left */, 2 /* Left */]],
    ['twO', [21 /* Peaceful */, 1 /* Neutral */, 0 /* Smile */]],
    ['o//o', [1 /* Neutral */, 1 /* Neutral */, 2 /* Neutral */, 0 /* Forward */, 0 /* Forward */, 1 /* Blush */]],
    ['o/////o', [1 /* Neutral */, 1 /* Neutral */, 2 /* Neutral */, 0 /* Forward */, 0 /* Forward */, 1 /* Blush */]],
    ['o\\\\o', [1 /* Neutral */, 1 /* Neutral */, 2 /* Neutral */, 0 /* Forward */, 0 /* Forward */, 1 /* Blush */]],
    ['o\\\\\\o', [1 /* Neutral */, 1 /* Neutral */, 2 /* Neutral */, 0 /* Forward */, 0 /* Forward */, 1 /* Blush */]],
    ['>//<', [23 /* X */, 23 /* X */, 2 /* Neutral */, 2 /* Left */, 3 /* Right */, 1 /* Blush */]],
    ['-//v//-', [6 /* Closed */, 6 /* Closed */, 0 /* Smile */, 0 /* Forward */, 0 /* Forward */, 1 /* Blush */]],
    ['-///v///-', [6 /* Closed */, 6 /* Closed */, 0 /* Smile */, 0 /* Forward */, 0 /* Forward */, 1 /* Blush */]],
    [';//v//;', [15 /* Sad */, 15 /* Sad */, 0 /* Smile */, 0 /* Forward */, 0 /* Forward */, 1 /* Blush */ | 4 /* Cry */]],
    [`6_6`, [1 /* Neutral */, 1 /* Neutral */, 6 /* Flat */, 7 /* Down */, 7 /* Down */]],
    ['6.6', [1 /* Neutral */, 1 /* Neutral */, 13 /* Kiss */, 7 /* Down */, 7 /* Down */]],
    ['bcd', [1 /* Neutral */, 1 /* Neutral */, 0 /* Smile */, 7 /* Down */, 7 /* Down */]],
    // TODO: o-o' o-o' ~_~ @_@ o=o oyo *_* (amazed) -_-/ -_-\ D_D
    // vertical (short)
    ['^^', [13 /* ClosedHappy2 */, 13 /* ClosedHappy2 */, 0 /* Smile */]],
    ['))', [1 /* Neutral */, 1 /* Neutral */, 0 /* Smile */]],
    ['((', [1 /* Neutral */, 1 /* Neutral */, 1 /* Frown */]],
    ['<<', [2 /* Neutral2 */, 2 /* Neutral2 */, 6 /* Flat */, 3 /* Right */, 3 /* Right */]],
    ['>>', [2 /* Neutral2 */, 2 /* Neutral2 */, 6 /* Flat */, 2 /* Left */, 2 /* Left */]],
    // vertical (invalid)
    ...[
        '---', '...', '000', 'QQQ', 'One', 'Up.', 'UP.',
        ...expressionUtils_1.THREE_LETTER_WORDS,
        ...expressionUtils_1.THREE_LETTER_WORDS.map(x => x.toUpperCase()),
        ...expressionUtils_1.TWO_LETTER_WORDS.map(x => x + '.'),
        ...expressionUtils_1.TWO_LETTER_WORDS.map(x => x + ','),
        ...expressionUtils_1.TWO_LETTER_WORDS.map(x => x + '-'),
        ...expressionUtils_1.TWO_LETTER_WORDS.map(x => x + '*'),
    ].map(x => [x, undefined]),
    ['BS', undefined],
    ['x8', undefined],
    ['8x', undefined],
    ['xx', undefined],
    ['-//c-', undefined],
    ['-c//-', undefined],
    ['030', undefined],
    ['80', undefined],
    // other
    [`aaaaa`, [1 /* Neutral */, 1 /* Neutral */, 16 /* ConcernedOpen3 */]],
    [`AAAAAA`, [1 /* Neutral */, 1 /* Neutral */, 16 /* ConcernedOpen3 */, 6 /* Shocked */, 6 /* Shocked */]],
    [`aaaaa...`, [1 /* Neutral */, 1 /* Neutral */, 16 /* ConcernedOpen3 */]],
    [`zzz`, [6 /* Closed */, 6 /* Closed */, 2 /* Neutral */]],
    [`ZZZZZ`, [6 /* Closed */, 6 /* Closed */, 2 /* Neutral */]],
    [`zzz...`, [6 /* Closed */, 6 /* Closed */, 2 /* Neutral */]],
    // emoji
    ['🙂', [1 /* Neutral */, 1 /* Neutral */, 0 /* Smile */]],
    ['😵', [1 /* Neutral */, 1 /* Neutral */, 0 /* Smile */, 1 /* Up */, 0 /* Forward */]],
    ['😐', [1 /* Neutral */, 1 /* Neutral */, 6 /* Flat */]],
    ['😑', [11 /* Lines */, 11 /* Lines */, 6 /* Flat */]],
    ['😆', [23 /* X */, 23 /* X */, 5 /* SmileOpen */]],
    ['😟', [15 /* Sad */, 15 /* Sad */, 2 /* Neutral */]],
    ['😠', [19 /* Angry */, 19 /* Angry */, 0 /* Smile */]],
    ['🤔', [1 /* Neutral */, 8 /* Frown2 */, 13 /* Kiss */]],
    ['😈', [19 /* Angry */, 19 /* Angry */, 0 /* Smile */, 1 /* Up */, 0 /* Forward */]],
    ['👿', [19 /* Angry */, 19 /* Angry */, 18 /* SmileTeeth */]],
    // unsafe faces
    [':L', [1 /* Neutral */, 1 /* Neutral */, 23 /* NeutralPant */]],
    [':Q', [1 /* Neutral */, 1 /* Neutral */, 22 /* SmilePant */]],
    // safe replacements
    [':u', [1 /* Neutral */, 1 /* Neutral */, 11 /* NeutralOpen2 */]],
    [':DD', [1 /* Neutral */, 1 /* Neutral */, 9 /* SmileOpen2 */]],
];
//# sourceMappingURL=expressions.js.map