"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const lodash_1 = require("lodash");
const stringUtils_1 = require("../common/stringUtils");
const otherChars = 'ąăãçćıłńęśóöøğüțţťżź';
const wordBreakRU = `[^a-zA-Z\u0400-\u04FF${otherChars}}]`;
const wordStartRU = `(?:^|${wordBreakRU})`;
const wordEndRU = `(?=$|${wordBreakRU})`;
function createBadWords(fast) {
    const emoji = fast ? '*' : '😀-🙏☀-⛿✀-➿🚀-🛶⬀-⯯🌀-🗿';
    const separators1 = `:;!|\`"@#$%^&'*,._=+~\\-`; // \\(\\)\\{\\}\\]\\[
    const separators2 = `${separators1}\\(\\)/\\\\`;
    const sep = `[ ${emoji}${separators2}]`;
    const sep2 = `[${emoji}${separators2}]`;
    const sep3 = `[${emoji}${separators1}]`;
    const sep4 = `[${emoji}${separators1}\\(\\)\\{\\}\\]\\[]`;
    const sep5 = `[ ${emoji}${separators1}\\(\\)\\{\\}\\]\\[]`;
    const sep2OrNum = `[0-9${emoji}${separators2}]`;
    const onlyLetterT = fast ? 't' : 'tţțťтᴛ';
    const letter = {
        a: '[aаáα@4åα]',
        b: '[bв🅱]',
        c: '[cсćčçḉĉɕċƈȼ¢ς©ᴄ<]',
        e: '[eе3єεęėëê€é]',
        f: '[fғƒꜰ]',
        g: '[gɢ]',
        h: '[hн]',
        i: '[ıιi!1íĭǐîïḯịȉìỉȋīįᶖɨĩḭᴉᵢ¡İ|🕯ɪ]',
        k: '[kĸкḱǩķⱪꝃḳƙḵᶄꝁꝅʞκᴋ]',
        n: '[nηɴñń]',
        o: '[o○о0σõø🍪🥚°]',
        p: '[pр]',
        s: '[sş5$š]',
        ss: fast ? 'ss' : '(?:ss|ß)',
        t: `[${onlyLetterT}^7]`,
        u: '[υuúŭǔûṷüǘǚǜǖṳụűȕùủưứựừửữȗūṻųᶙůũṹṵᴜ]',
        x: '[xх]',
        ь: '[ьЪ]',
    };
    if (fast) {
        Object.keys(letter).forEach(key => {
            letter[key] = letter[key].replace(/[^\u0020-\u007e]/g, '');
        });
    }
    const anyD = '(?:d|\\|\\))';
    const anyH = '(?:h|\\|-\\|)';
    const anyK = '(?:k|\\|<)';
    const anyL = '(?:l|\\|_)';
    const anyN = '(?:n|\\|\\\\\\|)';
    const anyO = '(?:o|0|\\(\\))';
    const anyU = '(?:u|\\|_\\||\\\\/|\\(_\\))';
    const wordBreak = fast ? `[^a-zA-Z]` : wordBreakRU;
    const wordStart = `(?:^|${wordBreak})`;
    const wordEnd = `(?=$|${wordBreak})`;
    // sp
    const oó = fast ? 'o' : 'oó';
    // pr
    const ã = fast ? 'a' : 'aã';
    const á = fast ? 'a' : 'aá';
    // ro
    const ă = fast ? 'a' : 'aă';
    const ț = fast ? 't' : 'tț';
    // pl
    const ą = fast ? 'a' : 'aą';
    const ę = fast ? 'e' : 'eę';
    const ć = fast ? 'c' : 'cć';
    const ń = fast ? 'n' : 'nń';
    const ł = fast ? 'l' : 'lł';
    const ó = fast ? 'u' : 'uó';
    const ś = fast ? 's' : 'sś';
    function separeted(letters, separator = sep) {
        return letters.split('').map(x => `${letter[x] || x}+`).join(`${separator}*`);
    }
    function baseSeparate(letters, sep, optional) {
        return `_*${separeted(letters, sep)}${(optional ? `(?:${separeted(optional, sep)})?` : '')}_*`;
    }
    function separate(letters, optional, separator = sep) {
        return baseSeparate(letters, separator, optional);
    }
    function separate2(letters, optional) {
        return baseSeparate(letters, sep2, optional);
    }
    function alts(letters) {
        return letters.split('').map(x => `${letter[x] || x}+`).join('');
    }
    let fuckWords;
    const badWords = [
        // english
        'aborted ?fetus',
        'all?(?:uh|ah ?u?a?|uah) ?a+c?k(?:ba+r*)?',
        '(?<!hea(?:r|w)ing|band) aids',
        'akbar',
        'anal(?:fisting)?',
        '(?:my|your|his|her)?a[*]?nus',
        'i want uranus',
        'a n u s',
        'poopoo hole',
        '(?:b[i1]tch|fat)?a+[s$]{2,}(?:es|fucks?| ?w?holes?|hats?|lickers?|wipes?)?',
        'arse? ?hole',
        'as[*]+ole',
        separate('asshole', 's'),
        'a[*]+h[o0]les?',
        'a+[sz2*$%#@&-]+h+oles?',
        'your a s s',
        'bootyhole',
        `a${sep2}?s${sep2}?s`,
        'a+ss+m+e+a+t+',
        'dumb a ss',
        'autis(?:ts?|ms?|tic)',
        'a *u *t *i *s *[mt]',
        'bend over',
        'bea?stiality',
        'lets bang',
        'bangs (?:her|him)',
        'son ?of(?: ?a)? ?(?:bitch|beach)',
        'beatch',
        'beach no',
        'you (beach|batch)',
        'bitv?c ?h',
        'b[%*]+ch',
        'b[i1][s$]h',
        'b[*]th',
        'b[*]{2,}s',
        `b(?:\\*|${letter.i})+[ae]*th?c+h+(?:e?[sz]+)?`,
        'b+i+t+s?c+h+',
        'bit?ach(?:es)?',
        'bit?<h(?:es)?',
        'b[it*]+ch(?:e[sz]+)?',
        'b+[i*]+c+t+h+',
        'b[hw]itch',
        'binch(?:es)?',
        'bio ?tch(?:e[sz])?',
        '(?:b|bi)[*]+(?:tch|ch|h)',
        'bi?y[ao]tch',
        'bi+ta+ch',
        'betch(?:es)?',
        'b *e +t *c +h',
        'b +i +o +t +c +h',
        'b-i-c-t-h',
        'b +i +c +t +h',
        'b\\.? *i *c\\.? *h',
        'biti?chi',
        'bit[sx]h',
        'bithc',
        'bitcj?',
        'bihtch',
        'b1ch',
        'bxitch',
        '(?:little|hi) b *e *a *c *h',
        `b${sep2}tch`,
        `b${sep3}{3,}h`,
        `b(?:${letter.i}|\\|)${letter.t}${letter.c}h`,
        'bi[ct] h',
        'bicht(?:es)?',
        'b[*]t[*]h',
        'b[*.]tch',
        'btc[*.]h',
        'bit[*.]h',
        'bi[*]{2}es',
        `b[i1]+s+h+(?:es)?`,
        'b[*] sh',
        `b${sep2}+s+h+(?:es)?`,
        'b(?:ei|ic)tc+h+e?s?',
        separate('bitch', 'es', sep5),
        separate('bietch', 'es'),
        separate('bictch', 'es', sep5),
        `b${sep2}(?:i${sep2}|t)ch`,
        '(?:you little|son of a) b',
        'bi tc',
        'b[i!1][t+]ch(?:es)?',
        'bitces',
        'bi1?t1?ch',
        'b+i+c+h+',
        'b[i1l]tch',
        'b\\|7h',
        'b\\(\\S+\\)tch',
        '\\S*lilbetch\\S*',
        '(?:bl[o0]w|hoof|foot|hand|rim) ?jobs?',
        'boners?',
        'bone ?(?:me|you|him|her)',
        'b[o0]{2,}b(?:i+e+[sz]|ie|s|z| ?jobs?)',
        'b[o0]{2}b',
        'b[. ]+o[. ]+o[. ]+b(?: s)?',
        'butt ?plugs?',
        'put+ in the butt',
        'in the but+hole',
        'bukake',
        'ballsacks?',
        'balls ?(?:deep|slapp?ing)',
        '(?:sweaty|his|lick my|empty my) ?balls',
        'my balls swell',
        '(?:butt|arse) ?holes?',
        'b[*]tthole',
        '(?<!died of )can[cs]er+(?:s|ous)?(?! patient)',
        'i hope you get (?:\\S+ )?cancer?',
        `(?<!died of )${separate('cancer')}(?! patient)`,
        '(?:horse|mare)?c\\Scks?(?! gun)',
        'c[o0][c<]k(?:socks?)?',
        separate('cock'),
        'co[cq]ksuckers?',
        'c[o0][ck]c',
        `c${sep2}[ck]c`,
        'cockhead',
        'his cok',
        'condo[nm]',
        'climaxe[ds]',
        '(?:his|her|has a|hit my) climax',
        'clit(?:o[*]?ris)?',
        'clopp(?:ing|ers?)',
        '(?:whale)?cum+(?:s|ing|ies)',
        'cum ?(?:dump(?:sters?)?|buckets?|guzzl(?:ing|ers?)|soaken|stain|huge load)',
        //'cum', // cant use because of spanish
        'cum (?:in(?:side)?|on) (?:your?|my|me|her)',
        'cum (?:inside|outside|spewing|for me|harder|a ?lot|more|all|stain(?:s|ed)?|slave|on (?:yo)?ur|squirts|'
            + 'fills|deep|massive)',
        'cum for(?!ç)',
        `(?:m[ey]|your?|i|h+is|warm|makes? u|me to|g[ou]nna|to not|more|make her|please|daddys|stallion`
            + `|will|they|can|swallows|salty|of|some|with|licks?|leaks|pls|in|from|sticky|the|her|its|spurt(?:s|ing)`
            + `|(?:going|start(?:ed|s)?|ready|about|get|want) (?:t-)?to|what|yes|did|don'?t|let'?s|say|i'?ll|zebra|and) cum`,
        'cum cum',
        'gonna c-cum',
        'i camm+e+',
        'c +u +m +(?:m +)+i +e +s',
        'cumme[rd]',
        'precum',
        'c(?:[*._-]n|u[*._-]|n[*])ts*',
        separate('cunt', 's'),
        'cunt(?:bo[iy]s?|lord|muffin|bags?)',
        `c${anyU}${anyN}t`,
        `c +${anyU} +${anyN} +t`,
        'c[.]unx?t',
        'cvnts?',
        'cxunt[sz]?',
        '(?:d[a4]dd?y|(?:bite|poke) me|do it) harder',
        '(?:(?:duck|rut) ?me|harder|oh ?yes|s-so big) ?d[a4]dd?[yi]',
        'd[e3]{2}p ?throa[t7](?:ing|s|ed)?',
        `(?:horse)?d[i!](?:<|${letter.c})k+s?(?:wads?|suck(?:ing|ers?)?)?`,
        'd[i*71!]+[c*]k+(?:les|face)?',
        'di\\[k',
        'dii+c+s?',
        'di+ +i+c+k+',
        'dic+s',
        'dicc+',
        'd[!?][(c]c',
        'dcks',
        'd[*] +ck',
        'di[ck]+ ?hea?ds?',
        separate('dick', 's'),
        separate('dicc', 's'),
        'limpdick',
        `di?${sep}c[ck](?:s|heads?)?`,
        `di?${sep}+ks`,
        'dick(?:girls?|hole)',
        'dikk',
        'd *l *c *k',
        'eat pee pee',
        '(?:your|my) d in (?:your|my) p',
        'suck (?:a|my) (?:d *i *c *k|d(?:ic)?)',
        '(?:my|your) di[ck]',
        '(?:my|your) d *e *k',
        'dildo(?:sa?)?',
        'dwildo',
        'd +i +l +d +o',
        'drink bleach',
        'do me hard',
        'ejaculat(?:e[sd]?|ing|ion)',
        'f[a*]p(?:p?ing)?',
        'f +a +p +p +i +n +g',
        separate('faps'),
        'foalcon',
        separate('fagot', 's'),
        separate('faggot', 's'),
        'fgt',
        'f ag',
        'dafag',
        '(?:normal|brony|furry?|gay|horse|pony|nigg?er)?f[a@]g(?:s|g?[0oi]t(?:s|ry)?)?',
        'f+a+g+s*',
        'f[ae]ggets?',
        'faguette',
        'fxaggots?',
        'fagatron',
        'fa[*]{2,}ots?',
        'f[a4][g69]{2,}[o0][t7]s',
        'fist( me|ing)',
        'fingering',
        ...(fuckWords = [
            'shut ?the ?fuck ?up',
            '(?:f[*]+|f[uy]ck|fuq|fvk) ?(?:ed|ers?|ing|face|you+|off+|u+|me|up|urself)',
            separate('fucking'),
            separate('fuckin'),
            separate('fucker', 's'),
            separate('focker', 's'),
            separate('fvck'),
            separate('fucc'),
            separate('fack'),
            'f[u ]+[c ]+k',
            'facken',
            'fucc(?:e?n|d)',
            'f[a4]ck[e3]d',
            'f *u *c *c *s',
            'fu[#$%&_]+(?:ed|ing)',
            'f[#$%&_]cki[#$%&_]?ng',
            'fuack',
            'fuk+a',
            'fukwad',
            'dufuk',
            'fux{2,}g',
            'fxxx',
            'g[ie]t fuk[td]',
            'f[vu]+ck',
            'fk +(?:ing|o *f *f)',
            'f *k i *n *g',
            'f *u *k *i *n *g',
            'fu(?:[qk]s|vk|cj|kn)',
            'fkc',
            'fvkn?',
            'fvcc',
            '\\S*f[uv]<k(?:ing|er)',
            'ufck(?:ed|ing)?',
            'fuck\\S+',
            `f${sep2}+uck`,
            'f[*] +ck',
            'f ucj',
            'f-?uckie',
            'fuq[qk]ing?',
            'fuqk',
            'fuke up',
            'fukd',
            'fcng',
            'fwu[ac]k',
            'f x u x c x k',
            'fuchs',
            'f[ou]ke+n',
            'fakiu',
            'f- u',
            'f *_+ *(k|u|everyone)',
            'fu<k',
            'f[.\\[]u[.\\]]k(?:you|me)?',
            'uck m e',
            'fu[*_.,-]+ing',
            'the f (?:up|away|out)',
            'fukbo[iy]',
            'the(?:fuck|fuk|fuccin)',
            'fuke me',
            'fu[*\\[]king',
            `fu${sep2}?ccs?`,
            `fuc${sep2}ing`,
            'fu[0-9]ing',
            `f${sep3}+(?:ng|ing|ed)`,
            `f${anyU} ?ck`,
            'Fu *sh *ck *it',
            'f u [*] [*](?: i n g)?',
            'flu+ck(?:ing?|er|s)?',
            'flu+c?k(?:ing?|er|s)',
            'f *o *c *k *i *n *g',
            'fakk+(?:in|er)?',
            'f00k(?:in|er)?',
            'fy+c+king',
            '(?:faq|f\\.\\.k) *(?:ing|er|this|dis|u|you|yoursel(?:f|ves))',
            '(?:fyuck|fcuk)(?:ing|er)?',
            '(?:brony|furry?|gay|horse|pony|nigg?er|butt|mother ?|mo|mutha|da|de)?'
                + 'f+[ou*8&%$#@]+[ck]+(?:ed|ers?|in[9g]?|able|faces?|balls?|toys?|ta+rds?|bo[iy]s?)?',
            'm[o0]therf\\S*',
            'm[uao](?:th|d)?af[au]c?k(?:as?|in)?',
            'moderfocke+r',
            'mothertrucker',
            'mother ?fukas',
            'm[aou]tha fu(?:kas?)?',
            'motha f',
            'mdfcka',
            'm[au]d[ai]f[au]c?kas?',
            'f+.?ck+(?:s|ed|er|ng|ing?|ign)?',
            'f.?u.?cking?',
            `f${sep}+cking`,
            `fu${sep2}+k`,
            'f[u*]\\[k(ing|er|s)?',
            `f${sep2}{2,}ing`,
            `f${sep2}{2,}g`,
            `f${anyU}k`,
            `f +${anyU} +k`,
            'fuc[k*]i(?:ng|gn)\\S+',
            'fuc(?:lk?|ken)',
            'foc(?:ki?-*ng?|uking)',
            'fuci(?:kn|nk)g',
            'fuxc*k(?:ing|er+)',
            'fxuck',
            '(?:mc)?f[zx]xk(?:er|ing)?',
            'fucvk(?:ing)?',
            'fuyck',
            'fuvkers?',
            'fuk+en',
            'fukign',
            'fooken',
            'fking?',
            'f+u+ic+k+',
            '(?:fac+|f-k) (?:me|you|him|her|them|off)',
            'fac{2,}',
            '(?:fk|f uk)(?:er|ing)',
            'fo+uo+co+k',
            'f[ _]*u[ _]*c[ _]*c[ _]?k?(?:me|you)?',
            'f *[^a-z ] *c *k(?: *e *r)?',
            'f[*]+[kgrd]',
            '(?:f+ ?k|ef+|fak|fek|fugk|fu|uck) (?:her|him|you|of+|out|me|urself|yourself)',
            '(?:e+f+|f+k+) u+',
            'f[u-]+ck(?:tard)?',
            '(?:phack|phuck?)(?:ers?)?',
            'f[.-]+ing',
            'fq(?:er|ing)',
            '(?:fak|fuq|fudge) (?:me|you|u)',
            'fa{2,}k',
            '(?:da)?fuqs?',
            'daf+u+q+',
            'f ?u [kq]',
            'f+a+c+k+',
            'f[_*]xk',
            'f[0-9*._]u[0-9*._]ck',
            '(?:go)?fukyou\\S*',
            'mcfuc[ck]ing?',
            'mother fu?',
            'what the fu?',
            'phcking?',
            separate('fucking', '', sep5),
            separate('fuced', '', sep5),
            separate('fock', '', sep5),
            `${separate('fuck', '', sep5)}(?:you|me|ed)?`,
            'f[^a-z ]+king',
            `f${anyU}${letter.c}k(s|ing|ed)?`,
            `f +${anyU} +${letter.c} +k(s|ing|ed)?`,
            'f[ .]+u[ .]+c',
        ]),
        'gang ?bang(?:ed|ing)?',
        'gtfo',
        'get(?:ting)? laid',
        'get \\S+ laid',
        'g-spot',
        'laid (?:me|you|her|him|them) hard',
        'lo[.]?lis?',
        `h *${letter.e} *n *t *${letter.a} *i`,
        'h+e+n+t+[b-z]?a+i+',
        'hentai[a-z]',
        'hen[*-]ai',
        'h[e*]nt[a*]i',
        'henta+i+(?:s+|heaven|hero|commie|tale)?',
        'h[ae4][i1]l ?h[i1]t+l(?:[e3]rs?|a)',
        'ha?i hitler',
        // `you(?:'re a)? hoes?`,
        `h${letter.o}[e3]s?`,
        `h[o0.]+${letter.e}s`,
        'h[o0]+kers?',
        'horn[*-]*y',
        'humps?(?: (?:me|you)|ing)',
        'i hope (?:your parents+|you|u) die',
        // 'go die',
        `(?:i${anyN}|self)c[e3]st(?:uous)?`,
        '(?:jerk|j[a@]ck)(?:ing|s)? ?off',
        'j +e +r +k +(?:s|i +n +g) +o +f +f',
        'jerk(?:ing)? (?:you|u|him|them) off',
        'jizz(?:ed|ing)?',
        'jihad',
        'kikes',
        'kys',
        `(?<!don'?t )k[i1] ?ll (?:ur|y[o0]u?r) ?s[e3]l(?:f|ves)`,
        'lub(?:ing|ed|e)',
        'marehood',
        'mast[ue]rbat(?:e[ds]?|ion|ing)?',
        'm[a4][s5]turb(?:ar|o|en?)',
        'm *a *s *t *u *r *b *a *t *e *[ss]',
        // 'milfs?',
        `m${anyO}an(?:s|ed|ing)?`,
        'molest(?:ation|ing|ering?|ed|s|ia)?',
        'molistiah*',
        '(?<!grammar )nazi(?:sts?|sm|s)?',
        `(?<!grammar )${separate('nazi')}`,
        'necrophile?',
        // '(?<!ojos |son )negr[o0]s', // nigger
        'negr0s',
        '(?:black|stfu) negros?',
        'negros? (?:be|die|are|is|everywhere)',
        'negr[.]os',
        'n[1i!*]?[g3]{2,}[eo]r[sz]?',
        'n[1i!*](?:qg|gq)[e3]r[sz]?',
        'n[1i!*]gg?r?[e3](?:rs?|st)?',
        'niges+t+',
        `n[1i!*](?:ggr|g+ah?|${letter.b}{2}a)s?`,
        `ni${sep2}{2}a`,
        `n${sep2}(?:gg|bb)(?:as?|ers?)`,
        'n *i *g *g *e *s *t',
        'nigg[sy]',
        'niqqer',
        'niggurs?',
        'nig(?:ro|let)',
        separate('niger', 's'),
        separate('nigger', 's'),
        separate('nigga', 's'),
        `nig:[a-z]+:ger`,
        'ngigers?',
        'niggars?',
        'nigx?gx?ers?',
        'nyggas?',
        'neegah',
        'n[i1]bbers?',
        'n[i1][g69]{2,}([e3]r|a)s?',
        'n [i1|] b b a',
        '7igga',
        'niqqas?',
        'ni9{2,}ers?',
        'nig a',
        'nya?-?ggers?',
        'knee+gur+',
        'n0*i0*g0*g0*a',
        'normies+',
        'nudes',
        'oral',
        'orga[sz]m[so]?s?',
        'urgazmo?z?',
        `o+r+g+(?:y+|ies|${letter.i}a)`,
        'piss(?:ing|face)?',
        'p[e3*]n[i1][s$z](?:es)?',
        separate('penis'),
        'p[e3]n[i1]s(?:[e3]h?s)?',
        'p[e3]{2,}ns?',
        'peepee',
        'peenus',
        'pengis',
        'penius',
        `b${letter.e}nis`,
        'pee(?:bnis|ner)',
        'p(?:ie|ea)ce of (?:shit|crap)',
        'pneis',
        'p[_*]nis',
        '(?:hard|surprise) ?penetration',
        'p[o0*]r[*]?no?',
        'pr[o0]n',
        `${separate('porn')}${fast ? '' : '(?![ãÃóÓ])'}`,
        '(?:child )?pornogra(?:fia|phy)',
        'pound(?:ing)? (?:me|you|her|him|us)',
        'prostitut[ae]s?',
        'prostate',
        '(?:octo|horse|pony|wet)?(?!puss ?in ?boots)pu+[s$5]{2,}(?:y+|ies+)?(?:juice)?',
        '(?:horse|pony|boi)?pw?u[s$5]+(?:y|ies|i)(?:juice)?',
        'horsephssuy',
        separate('pussy'),
        `p${sep}ssy`,
        'p[_*][s$5]{2,}y',
        'pyssy',
        'pussy(?!cat|foot(?:ing)?)\\S+',
        'pu[s$_-]{2,}y',
        'pussa[hy]',
        `p${anyU}[s5]{2,}y`,
        'p[o0]{2,}s+ay',
        'pus{2,}i',
        'p[uv][sz$5]+y',
        'poo+ *s+y',
        'r[a@*]e?p(?:i[s$]ts?|ing|[e3](?:ists?|ing|s|d)?)',
        separate('rapes'),
        separate('rape', 'd'),
        separate('rapist', 's'),
        'r/+p(?:ed?|ists?)',
        `r${sep2}pe[sd]?`,
        'r +a +p +i +n +g',
        `r${sep2}?a${sep2}?p${sep2}?e(?:s|d|ing)?`,
        'rhap(?:es|ed?|ist|ing)',
        '(?:eye|ass)rape',
        'raep',
        'r3pe',
        '(?:rap[*]|repe) +(?:yu|you|u|me|us|her|him|them)',
        '(?:wr|rw)ap(?:e|ists?)',
        'grape noises',
        'retard(?:s|ed|ads)?',
        separate('retard', 's'),
        'scr[e*]w(?:ing|ed)? (?:you|u|me|us|her|him|them|all)',
        '(?:[sz]ieg|s[ae]ig|[sz]ig) ?h[ae]il',
        'se[.]?men',
        'sea ?men',
        'cmen',
        'send nu+des',
        'sex(?: *slave| *abuser?)',
        '(?:anal|butt|oral)?(?:[s$]ex+8?|secks|seks)',
        '(?:anal|butt|oral) ?secs',
        's+[e3*&_]x+o*',
        's +[e*] +x',
        's *e *x',
        `${separate2('sex')}(?!${sep2}*y)`,
        'saex',
        'sexe',
        'have sax',
        'sexual(?:ly)?',
        'sax with e',
        'stf ?[uv]+',
        's +t +f +u+',
        'sc?hl?ongs?',
        '(?:my|his) shaft',
        '(?:bull|dip|oh|holy)?[s$]+h[i1*!]+e?t+(?:s|ing)?',
        's[*]+i?t',
        `s[#■]it`,
        '(?:bull|dip)?shite(?! (?:iru|ageru|kudasai))',
        'shite?(?:heads?|faced?)',
        'shit(?:head|stain|lord)',
        's+h[ie#]t',
        's#{2,}t',
        'shjet',
        `sh${sep2}t`,
        `s${anyH}[i!|][t7]s?`,
        `s +${anyH} +[i!|] +[t7]s?`,
        'holy ?shee+t',
        'shitt+y',
        's[0-9]?h[0-9]?i[0-9]?t[0-9]?s?',
        'shxit',
        'shota',
        'sl[u#*]t(?:s|ty)?',
        separate('slut', 's'),
        's(?:;l|l;)ut',
        's[*]ut',
        `s${anyL}${anyU}t`,
        's+p+e+r+m+a*',
        'spank me',
        'spicks',
        'spunk',
        'sucks? dic?k',
        '(c[o0]ck)?s *u *c *k(?:ing|er)',
        'c[o0]ck *s *u *c *k(?:ing|er)?',
        'sucks (?:balls|dic|harder|deeper)',
        `(?<!(?:it|that|this|which|school) )${separate('suck', 's', sep5)}(?! (?:(?:the )?blood|(?:(?:his|her|my|their) )?neck|at ))`,
        `${separate('succ', 's', sep5)}`,
        'sukks?',
        'suk my',
        'su[(<\\[]k',
        's *[u*] *c *cs?',
        `s${anyU}+c{2,}s?`,
        `s\\|_\\|+c${anyK}s?`,
        `s${anyU}+c\\|<s?`,
        `s +${anyU} +< +ks?`,
        'su[c<]{2,}(?:ed|ing)',
        's[*]cks',
        'su+[i|]?[c<]ide',
        'suic[*]+de',
        'tampon',
        'testicles',
        'the kkk',
        `t[_ ]+${anyH}[_ ]+o[_ ]+t([_ ]+s)?`,
        `t *\\|-\\| *[o0] *t`,
        'th0ts?',
        `th${sep}+ot`,
        'th:ots',
        'thotties',
        'sup thots?',
        'thrusts? into (?:her|him)',
        'tit(?:s|ty|ties?)',
        't\\[i\\]i?ts',
        'tiddies',
        't i t s(?! [a-z] )',
        `t *${letter.i} *[td] *[td] *${letter.i} *e *s`,
        'tranny',
        'touch my d',
        'wank(?:ing|e+r[sz]?)?',
        'wh[o0*]re+s?',
        'w\\Shore',
        'w *h *o *r *es?',
        'whorae',
        `w${anyH}${anyO}res?`,
        `w +${anyH} +${anyO} +r +es?`,
        'austic hore',
        separate('vagina', 's'),
        'v[*]gina',
        'vag[*]na',
        'vaginales',
        'vagina[a-z]',
        'vagin[ig]a',
        '(?:my|your|her) vag(?:ina)?',
        '[vb]aginal',
        'vagbo[iy]s?',
        'vibra[td]or(s|ima|om|es?)?',
        `v${anyO}r(?:e[sd]?|ing)`,
        'v[.-]?o[.-]?r[.-]?e',
        'vulva',
        '(?:white|wyte) ?(?:power|supremacy)',
        'yiff(?:s|ing|ed|ers?|u)?',
        'y i f f',
        'zo[o*]+(?:f|ph)ili(?:a+h?|cos)',
        // other
        'black ?supremacy',
        '(?:gas|kill)(?: (?:the|some|their))? jews?',
        'jews? burning',
        'x *v *i *d *e *o *s',
        'alt ?(?:[+-] ?)?f4',
        '(?:ctrl|control) ?[+-]? ?w',
        'touch +my +pp',
        '(?:my|your) dix',
        '(?:my|your) +p *p',
        'lick my pencil',
        'shoves? (?:my|your|his|her) horn into (?:me|you|him|her|them)',
        'rub my nipples?',
        // FOREIGN
        // bulgarian
        'nekoi hui',
        // dutch
        'hoer',
        // portuguese
        'estupra',
        'filho da puta',
        'caralho+',
        'pu?ta madr?e',
        'p+[uv*]+t+a+[sh]?',
        'p[uv]+tazoh?',
        `p${sep2}?u${sep2}?t${sep2}?ah*`,
        'p +u +t +a',
        'p[v¡]to',
        'putaria+',
        'ptazos',
        'p+o+rr+a+',
        'vadia',
        'malditos',
        'fud(?:er|ido)',
        'foda[ =-]?[sc]e+h?',
        'se fode',
        'f o d a - s e',
        'fodac?',
        'fodaci',
        'se fude(?:r|u)?',
        'm[e3]rdas?',
        `chupa+r? (?:me[ou]|minha|seu|su|mi) (?:p[${ã}4][ou]h?|rola|miembro|polla|pal)`,
        `chupa+r? *(tampones|pollas)`,
        'chupa(?:le|ndo) ?(?:la ?)?(?:tetas|punta)',
        't3t4s',
        'chup(?:a|a[rs]|enle) ?(?:el ?)?(?:ano|orto)',
        `(?:lo )?chupa (?:a (?:minha|salsicha)|r[${á}]pido|entero)`,
        'chupale ?mejor',
        'chupamela',
        'lo chupa',
        `chupando (?:a salsicha|forte|m[${á}]s fuerte)`,
        'meu pau',
        'soplame(?: el)?(?: pito)?',
        'sexo+',
        'penetra+ fort(?:e|ao)',
        'do pau dele',
        'cima do pau',
        'tocar no pau',
        'lamber meu rabo',
        // spanish
        'ca[zx]{2,}[o0i]+',
        'c[a*4]+r[a4]jo',
        'coje rejalo',
        'c[o0]j[e3]r(?:conmi|h+)?',
        'chingar?(?: tu madre)?',
        'chingados',
        `chup(?:o|ando) (?:fuerte )?tu pe[sz][${oó}]n`,
        'chupo con fuerza',
        'chupo(?: mas)? rapido',
        'sigue chupando',
        'cule(?:ro|ar)',
        'f[o0]ll[.]?[a4](?:r(?:[ms]eh?)?|mos|da|s)?',
        'gilipollas',
        'hij[ao]s? de? pt[ao]',
        'inbesil',
        'jop[uv]tas',
        'j[o0]d[a4]+s',
        'j[o0]d[e3a4]r',
        'j[o0]dier[o0]n',
        'mi[e3]rda+h*',
        'tu miembro',
        'mrda',
        'matate',
        'mereces morir',
        'n[oi] mereces vivir',
        'n[e3]pes?h*',
        'maric[o0]n',
        'p[uvw#*.]t[ao][zhs]*',
        'pollas',
        'pvtaso',
        'pu[.]?t[ao]',
        'puti[.]?ta',
        'p[uv]t[a4](madre|kos)',
        'p[t7][ao]',
        'pij[.]?a',
        'se le corre',
        'sou foda',
        'suicidat',
        'violando(?! la)',
        `v1${letter.o}l[eo]`,
        `[vb][i1]${letter.o}l[a4]r`,
        `vi0lare`,
        `[vb]1${letter.o}laci${letter.o}nes`,
        'violo a',
        'la viole',
        'la mete',
        'lamer la punta',
        '[bv]ete ?a ?la ?[bv]erga?',
        'v[e3]?rga',
        'zemen+',
        'zorra',
        // italian
        'arrap(?:at[eiao]|ano|are|[oi])',
        'bagasci[ae]',
        'baldracc(?:a|he)',
        'bastard[eiao]',
        'bocchin(?:[io]|ar[ae])',
        'bordello',
        'butt[ao]n[ae]',
        'cagna',
        'cagare',
        'k[a4]g[a4]r',
        'caghi(?:amo)?',
        'caga(?:no|te)',
        'cazz(?:on[iae]|at[ea])',
        'checc(?:a|he)',
        'chiav(?:o|are)',
        'chia?[bv]at[ae]',
        'c[o0]glion[aie]',
        'cortigian[ae]',
        'culatton[ie]',
        'ditalin[io]',
        'ebet[ie]',
        'eiacul(?:i|o|are|azione)',
        '(?:vaf)?fanculo',
        'fanculizzati',
        'fotte(?:te[lvm]i|re)',
        'fott[io](?:[tm]i|l[oaie])?',
        'fottut[aeio]',
        'frocio?',
        'fregna',
        'gigolo',
        'gnocc(?:he|a)',
        'handicappat[aeio]',
        'la figa',
        'negraccio',
        'perra+',
        'pirla',
        'p[e3]l[o0][t7]ud(a|o|ito)',
        'p[e3]?n[.]?dej(a+|o+h?s?)',
        'p[e3]nej(a+|o+h?s?)',
        'poll[.]*as',
        // 'porco', // pig
        'pompin(?:[io]|ar[ieao])',
        'puth?[o0]s*',
        'putada',
        'puttan(?:[ae]+s?|at[ae])',
        'prostitu(?:irsi|zione)',
        'scopa(?:ndo|mi)',
        'incazza(?:t[aeio]|rsi)',
        'incul(?:o|i(?:amo)?|a(?:rti|li|lo|la|no|te|re)?)',
        'lecc(?:hin[io]|acul[io])',
        'masturb(?:[ai]h?|alo|ami|are|arsi|azione|ate(?:li|vi)|iamol[oi]|iamoci|ando|as)',
        'merdos[ao]',
        'meretric[ie]',
        'mignott[ae]',
        'minchi(?:[ae]|at[ae]|on[iea])',
        'masturbarmi',
        'rompi(?:palle|coglioni)',
        'ricchion[ie]',
        'rincoglionit[ieao]',
        'sborr(?:o|a|ano|ate|i|iamo|are)',
        'sburro',
        'scopal[ao]',
        'scopar[tm]i',
        'scassacazz[io]',
        'sesso+',
        'sessuale',
        'segaiol[io]',
        'sfott(?:[io]|ere)',
        'sgualdrin[ae]',
        'spomipina',
        'spompina(no|re)',
        'stupratore',
        'sputtan[ai](?:l[io]|no|amo|t[aeio]|re)?',
        'sputtaniamol[oi]',
        'stronz[eaio]',
        'stronzat[ae]',
        'stupro',
        'zoccol[ae]',
        '(?<!la )pene',
        'el pne',
        'vagine',
        'troi[ae](?:io|h)?',
        'trombare',
        'tromb[io]',
        'trombate',
        'trombano',
        'trombal[ao]',
        'trombiamo(?:l[eiao])?',
        // 'fica', // pussy
        // finnish
        'perkele',
        'vittu',
        // french
        '(?:fils de )?pute',
        'pute(?:u+h+)?',
        'merde',
        // sweedish
        'fitta',
        // german
        'arsch',
        'fotzen?',
        `schei${letter.ss}\\S+`,
        '(?:[gb]e)?schissen',
        '(?:[gb]e)?(?:wichs|kack|fick)(?:est|en|et|e|test|te|t|st)',
        '(?:[gb]e)?(?:piss)(?:est|en|et|test|te)',
        `hurens(?:oe|[${fast ? 'o' : 'öo'}])hne?`,
        'huren',
        'schlampen?',
        'schwuchteln?',
        'neger',
        'wichser?',
        'wixxer?',
        'verpiss ?dich',
        'verdammter',
        'm[ea]in ?kampf',
        'lutsch meinen schwanz',
        // other
        '9/11',
        // sexually suggestive
        'against (?:her|his|your) insides',
        'creamy load',
        'empty my load',
        'cherry got popped',
        'into (?:her|your) (?:cervix|uterus)',
        'tight cervix',
        '(?:my|his|her|your) crotch',
        'panting heav(?:il)?y',
        'pegs her',
        'penetrat(?:es?|ing) (?:him|her|you|your)',
        'put(?:s|t?ing) (?:it|that) in (?:your|my|his|her) mouth',
        'pounds? (?:against|her|deeper)',
        'pump(?:ing)? my (?:large )?(?:seed|load)',
        'pushes (?:my tongue|deeper inside)',
        'pushing deep',
        'prodding my tip',
        'gets it inside',
        'goes (?:harder and |in )?deeper',
        'groans and th?rusts',
        'grabs her breasts?',
        'grinding her',
        '(?:starts|keeps|begins) thrusting',
        'thrusting (?:her|his|him|(?:even )?harder)',
        'thrusts? (?:slightly )?(?:deep|hard)(?:er)?',
        'thrusts? (?:my tongue|against)',
        'tongue inside',
        '(?:thick|my) hot load',
        'thick and creamy',
        'tight walls',
        'fast and (?:hard|deep)',
        'forcing every inch inside',
        'hard and deep',
        'her slit',
        '(?:her|his) nether regions?',
        'faster and (?:deeper|harder)',
        'fully erect',
        'deeper and harder',
        'harder and (?:harder|faster|rougher|deeper)',
        'filling her up',
        '(?:his|my) knot',
        '(?:her|your) (?:wombs?|wet cave|wet tunnel)',
        'her plothole',
        'kisses (?:him|her) lewdly',
        'womb with his',
        '(?:he|gently) thrusts',
        '(?:sticky )?(?:hot|warm) loads?',
        'hot seed',
        'seed into her',
        'mare juices?',
        'milk(?:ed|ing) him',
        'my fluids',
        'makes (?:you|u) squirt',
        '(?:his|your|my) (?:huge )?member',
        'pushes member (?:inside|into her)',
        'inside of her(?! mind)',
        `(?<!hold me |hugs |it'?s )so tight`,
        'fingers (?:inside )?her',
        'release my (?:heavy )?load',
        'rubs? her area',
        'screams in pleasure',
        'slides it in and out',
        'shoves (?:my tongue|the rest in)',
        'shoots out jizz?',
        'starts? (?:pounding|thrusting)',
        'sticks tongue in',
        'squirts on (?:your|his|her) face',
        'spreads her legs',
        'spraying (?:your|his|her) insides',
        't-tight',
        'tailhole',
        'throbbing hard',
        'with each thrust',
        'your dirty hole',
        `you're so wet`,
        // russian
        'pidor[sy]?',
        'pizdec+\\S?',
        'huinya',
        'kurva',
        'blyad',
        'bliat',
    ];
    const badWordsForeign = [
        // romanian
        `suga ?pul[${ă}]`,
        'muie',
        `s[${ă}] ?te ?fut`,
        `futu-?[${ț}]i ?pizda`,
        ...(fast ? [] : [
            'pulă',
        ]),
        // polish
        `ci+p(?:a{2,}|ę|ą|k(?:ami|[${ą}]|[${ę}]|i|owate|o)|ek|eczka|usie[${ń}]ka|ule[${ń}]ka)`,
        'chu{2,}j',
        'chuj(?:u|ek?|ami|a)',
        '(?:ten|w) chuj|chuj wie',
        'c?huj (?:ci|wam|w dupe)(?: w dupe)?',
        'c *h *u *j *[eua]',
        'huj[aeu]',
        'huj ?pizda',
        'cycki',
        // 'debil(?:[aie]|ami|em)?',
        'kutas(?:y|ami|iarzu?)?',
        'pornosy?',
        `dziwk(?:ami|om|[${ą}${ę}io])`,
        `k[.*]+rwa`,
        `kurwa ?ma[${ć}]`,
        `k *u *r *w *a(?: m a [${ć}])?`,
        `k[${ó}]+r[w*](?:ie|ami|y+|[${ę}]+|[${ą}]+|om|o+)x*`,
        `ku${sep2OrNum}+r?w(a+|o+)`,
        'ku[*]{2,}a+',
        separate('kurwa'),
        `wkurwi[${ł}][ay]?`,
        `wkurwia*(?:sz|my?|j[${ą}]?|[${ć}])?`,
        'skurwiel(?:em?|ami|i|a)?',
        `pi[z*]d[${ą}${ă}${ę}y]`,
        `(?:roz|ja|s|wy?)?pierd[o*]l(?:[${ę}]|i?cie|isz|i[${ł}](?:[ao]|[ae][${ś}])|i[${ć}]|eni|e|on[eay]| si[${ę}])?`,
        `roz[*]+ba[${ć}]`,
        `(?:s|za|wy?)pier?(?:[d*]a|[da*])la(?:jcie|j[${ą}]?|my?|cie|[${ć}])?`,
        `(?:s|za|wy?)pieprza(j|[${ć}]|j[${ą}]|jmy)`,
        `z?g[wf]a[u${ł}](?:t|tem|ty|tów|tami|cenie?|ceni|con[aey]|c[eoąi]|[${ć}]my|ci[${ć}]|ci[${ł}]+[iay]|cimy?)`,
        '(?:za|wy|z|u|na|prze|po|roz|przy)?'
            + `je+[b*](?:ie(?:sz|my)?|i[${ą}]|a+[*]?n[yaei]+(?:mi|m|go)?|a[${ł}][aeiyo][m${ś}]?|a+[${ć}${ł}]|a[${ń}]ce)`,
        `jeb(?: ma[${ł}]e)? dzieci`,
        `(?:wy)?r${sep2OrNum}*ucha(?:my?|jmy|jcie|j[${ą}]?|[${ć}]|nym?|n[ae]|nie?)`,
        'peda(?:le|lsk(?:ie|im|i|a)?)',
        ...(fast ? [] : [
            `pe[d*]ał(?:y|a|em|ami|[${ó}*]w)?`,
            'gówn(?:o|a|iaki?)',
            'suką+',
            'żesz chuj',
            'fapać',
        ]),
        's *p *i *e *r *d *a *l *a *j',
        'p *i *e *r *d *o *l *e',
        'j *e *b *a *n *[aeyi]',
        'p *i *e *p *r *z *s *i *e',
        `g *w *a *[${ł}] *t`,
        'fapie',
        `zabij ?si[${ę}]`,
        `wejd[${ę}] w ciebie`,
        `w dup[${ę}]`,
        'morda psie',
        's[.]*u[.]*k+aa+',
        's[.]*u[.]*k[.]*k+a+',
        'su ka',
        // spanish
        ...(fast ? [] : [
            'coño+',
        ]),
        // czech
        ...(fast ? [] : [
            'srát',
            'piča',
        ]),
        // turkish
        'sikiyimmi(?: seni)?',
        ...(fast ? [] : [
            'göt(?: ?k[ıI]l[ıI]| ?veren)?',
            'orospu(?: ?çocuğu)?',
            '(?:anan[ıI] ?|ecdad[ıI]n[ıI] ?)?sikiyim',
            'ana?nı sikim',
            'am[ıI]na ?koyayim',
            'amc[ıI]k',
            'yarra[ğg][ıI]m[ıI](?: ?ye)?',
            'sikiş',
        ]),
        'seni ?sikerim',
        'sikiyim',
        'siktir(?: ?git)?',
        'yarrak(?: ?kafa)?',
        'orospu',
        // russian
        'cy[k*]a ?(?:bl(?:ye|a|ie+)t+|bylat|blyt|blayt|bl[*]at)',
        '[sc][uy]ka ?bl[yiue]*?a[td]?',
        'b-?l-?y-?a-?d',
        'pisda',
        'bly+a+t+',
        'blya{3,}',
        'c[*]{2,}a',
        'cykablye+t',
        'cykaxd+',
        'cyak ?blyat',
        'ckya',
        separate('blyat'),
        separate('cyka'),
        '(?:cyka)+',
        'c ?ica blia',
        'govno+',
        ...(fast ? [] : [
            'б/?\\\\yat',
            'суда вручат',
            'анал(?:ьные)?',
            'а +н +а +л',
            'бля(?:ть)?ъ',
            `(?!бл ять|б лять)${separate('блять')}э?`,
            '[cс][yу][0-9]*[kк][aа]+',
            separate('сука'),
            'су\\dка',
            'су[57]+а',
            `с${sep2}+ч?ка|су${sep2}+а|сук${sep2.replace(/[.,!?"'()]/g, '')}+`,
            '[сc][*]{2,}[аa]',
            'с[*]{3,}',
            'сцука+',
            'Сюка',
            '[*]+ка',
            'с+у+к+и+н?',
            'сук[оo0]+',
            'секс(?:ам|а+|е|у|ом)?',
            'срать',
            `(?:вы|по)?е[б6]+[*]?(?:у|учая|ётесь|а?ться|а+т[ьъ]+|ало?м?ъ?|на|ались|аные|ан+ая|[*])`,
            `(?:вы|по)?е[б6]+${sep2}(?:у|тесь|ться|ть|лись|ные|н+ая|чий|чие)`,
            'е[б6]етс',
            'я *ебаl',
            'выепать',
            'влагалища',
            'вибратора?',
            `е${sep2}?[б6]${sep2}?[ёуа]${sep2}?ть?`,
            'е[б6](?:ать?ся+|ёнок|.ть|анный|алом?ъ?|нулся|нутая|анутся)',
            'з[б6]ать',
            'бл[*]{2,}ь',
            'б[л*]я(?:.ь|[яа]*)',
            '(?:е|лэ)?б+[лl]+[я*]+(?:ч|т+ь+э?|т+б*|дина|ди|дь|дя)?',
            `б(?:л${sep2}|${sep2}я+|${sep2}{2})ть`,
            'бл[эая]ть',
            'б[*]+[ья]+',
            'зае[б6](али?|лся)',
            'з[*]ебуьс',
            'е[б6]а',
            'е[*]б',
            separate2('заебал'),
            separate2('бля'),
            'з[а_*]еб[а_*]ли?',
            'б *л *я',
            'вы[*]+',
            'говно+м?',
            'мать твою',
            'онанист',
            'орг(?:ия|азм)',
            'охуительны(х|е)',
            'о[б6]осса(на|ть)',
            'шалаву',
            `ш${sep2}?л${sep2}?ю${sep2}?(шк[аa]+|[хx]и|[хx][аa]+)`,
            'ш +л +ю +(ш +к +а|х +[иа])',
            'шл[_*]ха',
            'пенис',
            'потрахались',
            'тр[а@*]х(атьс(еб)?я|аьт|нула|алаъ)',
            'дрочить',
            'порнухой',
            'изн[ак]силую',
            `у?пи[*]?[3з${emoji}]+д(?:абол(?:ка?)?|ое[б6]+учий|овать|овал|олизка|ы|а|ецъ?|е|юк|уйте|уй|ос?)`,
            'п[_*]здец',
            `письки`,
            'киск[иеуа]',
            'сперму',
            'кончи(?:л|шь)',
            'пид[о0]+р(ы|а[зс])?',
            `п${sep2}здуй`,
            'ниггеров',
            'мудак[аи]?',
            'лохи',
            'соси писос',
            'сосу член',
            'члено(?:м|соса?)',
            '(?:иди)?на[хx]уй',
            `[хx]${sep}ль`,
            '[хx]ерню',
            '(?:н[аa])?[хx][уy*]+[йи]+(?:ло|ка|э|у+|ъ+|н[ёе]й|н[юя]?)?',
            'н[.]*а[.]*х[.]*у[.]*[йи]',
            '(?:ху[йя])+',
            'ху[\\\\/]*ли',
            'х[_.*]ли',
            `ху${sep}+[йи]`,
            `[хx]+${sep}?у+${sep}?[йия]+${sep}?у*`,
            `[хx][${emoji}](?:[йия]|ёв)`,
            `[хx]у[${emoji}]`,
            `на(?:${sep2}у|х${sep2})[йи]`,
            '(?:ни|на|ha)?хер(?:а|ней)?',
            `(?:по|идина)?х(?:у|${sep2})[йию](?:ло|лестия)?`,
            '(?:по|на)\\)\\(у[йию]',
            'мастурбация',
            `[хx] *${sep2}+ *у *${sep2}+ *й`,
            `п(?:а|${sep2})дика`,
            'насил(?:ьник|уют)',
            'ни[хx]уя',
            'на[*]+й',
            'н[*]{3,}й',
            'насрать',
            'дерьмо',
            'дебилы?',
            'ты еб',
            // 'дохуя', // f*cking much (shitload)
            '\\bхуе\\b',
            'за(?:сранец|лупа|дницу)',
            'гавном?',
            `т${sep2}?р${sep2}?а+${sep2}?[хx](?:ни(?:те)?|нуть|ну|ает|а+ть)?(?: (?:тебя|меня))?`,
            'жоп(?:у|ай?)',
            `про[е${emoji}]бал(?:ся)?`,
            'анал',
            '3===+э',
            'зиг ха[ий]?ль',
            '(?:на|г|б)[*]{2,}',
            '(?:наша|нас|моя|моей) ?(?:территори[яи]|терра)',
            'кунт',
            'х[*]{2,}',
            '[Ъb][*іi][тt][cc][нh]',
            `\\)\\(${sep}?у+${sep}?[йия]+${sep}?у*`,
            'fuск\\S*',
        ]),
        // en
        'b[i!]tc\\|-\\|',
        'di(?:l|\\|_)d(?:o|\\(\\))',
        '(?<!grammar )n[a4]z[i1]s?',
        'fu[*-]{2}',
        'sh[*-]{2}',
        'wh[o0]r3s?',
        '\\*{4}(?:ed|ing)',
        '\\|\\\\\\| *[i1] *[g9] *[g9] *e *rs?',
        '[$]+(?:hit|perm|luts?|uck(?:ing)?|ex)',
        'tit',
        '[a@]+[s$]{2,}',
        'pi[$]{2,}',
        '[abcdfsn][*#]{2,}',
        'bit?[*]{2,}',
        'fu[*]+',
        'bic[*]+',
        '\\*+(?:ck)?ing',
        '(?<!-)se[*]',
        '(?:di|sh|ra|bi)[*]{2,}',
        '\\*sshole',
        '\\*{3}hole',
        `\\/\\|\\/iggers?`,
        'su\\(\\(',
        'd[i!1](?:\\(\\(|\\|<)',
        `c${anyO}c\\|<`,
        'f[o0][ck]\\(',
        'f[o0]\\([ck]',
        'f [o0] \\( [ck]',
        `${letter.c}${letter.o}${letter.c}${letter.k}`,
        `w${letter.h}${letter.o}r${letter.e}`,
        // japanese
        'ファックユー?',
    ];
    const badWordsOther = [
        '👉👌',
        'sexoanal',
        'masturbar',
        'cykably[ae]t',
        'autists?\\b',
        'bitch',
        'pussy(?!cat|foot(?:ing)?)',
        'nastyhoe',
        '(?:^| )irape',
        'rapechild',
        'ifinger',
        '^negros[.!?]*$',
        'f[a@]+[g3]+[eou0i]ts?\\b',
        'fags?\\b',
        '\\bfag(?:g|o)ot',
        `${alts('fuck')}(?:${alts('ing')}|${alts('er')}s?)?`,
        '\\bfuk(?:you|ass|of+)',
        'f[au]ck(?:er[sz]?|ing)',
        'fuking',
        'fvkin',
        'fvck',
        'fu(?:ck|kc)',
        'f +u +c *k',
        '^a s s$',
        'fukin',
        '[*]+exual',
        '(?:^| )ʞɔnɟ(?: |$)',
        '(?:^| )[aα]ss(?: |$)',
        '(?:^| )[a4]n[a4]l(?: |$)',
        '^beaches$',
        `(?:^| )b *[i!] *t *c *${anyH}(?: |$)`,
        `(?:^| )f *${anyU} *${letter.c} *${anyK}(?: |$)`,
        '(?:^| )fv\\|<(?: |$)',
        '(?:^| )fu[#&%_]{2,}(?: |$)',
        '(?:^| )fu\\[\\|<(?:ing|er)?(?: |$)',
        `${separate('fuck', 's')}`,
        '(?:^| )cum~+(?: |$)',
        '(?:^| )[*]+cum[*]+(?: |$)',
        '(?:^| )dild0\\d*(?: |$)',
        `(?:^| )${alts('cunt')}(?: |$)`,
        `(?:^| )${alts('tits')}(?: |$)`,
        `(?:^| )${alts('bitch')}(?: |$)`,
        `(?:^| )${alts('penis')}(?: |$)`,
        `(?:^| )${alts('nigga')}(?: |$)`,
        `(?:^| )${alts('nigger')}(?: |$)`,
        '(?:^| )n[i1][g69]{2,}[a4][s5]?(?: |$)',
        `(?:^| )\\|\\\\\\|az[i|]s?(?: |$)`,
        `(?:^| )\\|-\\|e${anyN}ta[i|](?: |$)`,
        `(?:^| )\\$${anyH}it(?: |$)`,
        `(?:^| )sh[i1!][+](?: |$)`,
        `(?:^| )👃unts?(?: |$)`,
        `(?:^| )d${letter.i}${letter.c}${letter.k}(?: |$)`,
        `(?:^| )${anyD}[i1][c(]k[s$]?(?: |$)`,
        `(?:^| )stf${anyU}(?: |$)`,
        `(?:^| )s +t +f +${anyU}(?: |$)`,
        `(?:^| )\\$hithead(?: |$)`,
        `(?:^| )${letter.s}${letter.e}${letter.x}(?: |$)`,
        `(?:^| )${letter.p}${letter.o}r${letter.n}(?: |$)`,
        `(?:^| )p${letter.o}rn${letter.o}+h*(?: |$)`,
        `(?:^| )p[*]rn${letter.o}+(?: |$)`,
        '(?:^| )l[o0]l[i1](s|x|cons?)?(?: |$)',
        '(?:^| )[*]humps[*](?: |$)',
        `(?:^| )${letter.o}+r+g+(?:y+|ies|${letter.i}[a4])(?: |$)`,
        `(?:^| )${letter.o}rg${letter.a}sm(?: |$)`,
        `(?:^| )${letter.o}v[e3]r?s[e3]x[e3]d(?: |$)`,
        `(?:^| )${letter.o}r4l(?: |$)`,
        `(?:^| )h[e*]nt[a*][i1](?: |$)`,
        `suckmydick`,
        '^(?:(?:sup|hi|hey|you) )?botch[!.]*$',
        // spanish
        '(?:^| )an[0○](?: |$)',
        '(?:^| )(?:ort0|0r[t7][o0])(?: |$)',
        '(?:^| )m[i1][e3]rd4(?: |$)',
        '(?:^| )mi?er[d#][#]+(?: |$)',
        '(?:^| )maric[a4](?: |$)',
        '(?:^| )c[a*4]+r[a4]j[o0](?: |$)',
        '(?:^| )caralh[0#](?: |$)',
        '(?:^| )put[04#]+[sh]*(?: |$)',
        `(?:^| )p${letter.u}t${letter.a}(?: |$)`,
        `(?:^| )pu[*]{2}(?: |$)`,
        `(?:^| )p[vw]t${letter.o}(?: |$)`,
        `(?:^| )pvt${letter.a}[s!]?(?: |$)`,
        `(?:^| )pvt${letter.a}s[o0]s(?: |$)`,
        `(?:^| )-*pv?t${letter.a}z[o0]h?-*(?: |$)`,
        '(?:^| )p[t7][@0](?: |$)',
        '(?:^| )(?:chupa(?:r|me) la )?p[i1]j4h?(?: |$)',
        '(?:^| )p[e3]?nd[e3]j0[sz]?(?: |$)',
        '(?:^| )(p4j[a4]|paj4)(?: |$)',
        '(?:^| )p[e3€]n[3€]h*(?: |$)',
        '(?:^| )p[3€]n[e3€]h*(?: |$)',
        '(?:^| )porr[@#](?: |$)',
        '(?:^| )su<<(?: |$)',
        '(?:^| )fod[4@#](?: |$)',
        '(?:^| )c[o0]ñ[o0](?: |$)',
        '(?:^| )cul[o0](?: |$)',
        '(?:^| )n[e3]p3(?: |$)',
        '(?:^| )a[_]?[s$5]{2}(?: |$)',
        '(?:^| )\\/\\\\[s$]{2}(?: |$)',
        '(?:^| )\\+turbar(?: |$)',
        '(?:^| )kg4rl4(?: |$)',
        '(?:^| )[*]viola[*]?(?: |$)',
        '(?:^| )v[e3]?rg[a4](?: |$)',
        '(?:^| )b[e3]?rg4(?: |$)',
        `(?:^| )[vb][i1]${letter.o}l[03](?: |$)`,
        `(?:^| )s${letter.e}x${letter.o}(?: |$)`,
        '(?:^| )p[e3]l[o0][t7]ud0(?: |$)',
        '(?:^| )j[o0]d[e3]t[e3](?: |$)',
        'suicidate',
        // portuguese
        '^[* ]*chupando[* ]*$',
        ...(fast ? [] : [
            '(?:^| )6+ля(?: |$)',
            '(?:^| )6лять(?: |$)',
            '(?<!бар)с+[у*]+ч*к+а+',
        ]),
        '(?:^| )fu[(|]<(?:ing)?(?: |$)',
        `(?:^| )${alts('nigger')}(?: |$)`,
        `(?:^|^${sep4} ?|\\S\\S | U )f+ +(?:her|him|you|of+|out|me|urself|yourself|everyone|admins|mods|moderators|my life|harder)\\b`,
        `(?:^|[ \\(\\)\\{\\}\\]\\[:;!|\`"@#$%^&*,._=+~\\-])(?!(?:s+hh+|ss+h)[ .,!-]+it)${separate('shit', 's')}\\b`,
        '(?:^| )[a][*#]{2}( |$)',
        '\\bbi.ch\\b(?! tree)',
        '\\bc+[y*]+u*k+a+\\b',
        '^cum$',
        '^fu?[*]+(?: |$)',
        ' fu?[*]+ ',
        '[a-z]{2,} f+[*]* +u+$',
        '\\bf{2,}[*]* +u+$',
        '^f+[*]* +u+(?= +[^a-z ])',
        '^f+[*]* +u+(?! *s *i *o *n)(?= +[a-z][a-z]+)',
        '^f+[*]* +u+$',
        '^f u c$',
        '^fak$',
        `(?:^| )${sep3}{2,} *(?:uck+(?:ing)?|itch)(?: |$)`,
        `(?:^| )${sep4} *(?:uck+(?:ing)?|itch)(?: |$)`,
        '\\bf[@#$%^&*]{2,}(?: |$)',
        '(?:^| )[*]{3,} (?:her+|him+|you+r?|of+|out|me+)\\b',
        '(?:^ *|[^s ] +)h +[o0] *e *s?\\b',
        `(?:^|${sep})di${sep}[ck](?:$|${sep})`,
        '8[:=-]{3,}[|]?[oD3>][-~]*',
        '8==[|]?[oD]',
        '8[ =]{2,}D',
        '(?:^| )[.][i|][.](?: |$)',
        'c[=-]{3,}3',
        '(?:^| )n [i!] g g [e3] s [t^](?: |$)',
        `(?<!\\bi)${wordStart}${alts('tho')}[${onlyLetterT}]+${wordEnd}`,
        'child *porn',
        '\\Sporn\\b',
        'nigger',
        'childrapist',
        'rapeyou',
        '\\brapist',
        '(?:\\bg|being)rape?(?:ing|d)\\b',
        'rule *34',
        '[48]chan\\.',
        '^aids$',
        '(?:p[o0]rno?hub|redtube|lemonparty|brazzers|youporn|xvidios)',
        'yiffyiff',
        // russian
        '[(]+[yу][kк][aа]',
        // polish
        fast ? 'jeban[aey]' : 'jeba(?:ć|ł[ay]?|n[aey])',
        'rozjebie',
        'spieprzaj',
        'odpierdol ?sie',
        // japanese
        '(?:^| )くそ(?: |$)',
    ];
    const badWordsSpecific = [
        '\\bgRAPE\\b',
    ];
    return { all: badWords, foreign: badWordsForeign, other: badWordsOther, specific: badWordsSpecific, fuck: fuckWords };
}
if (DEVELOPMENT && false) {
    (function () {
        const words = createBadWords(true);
        let failed = 0;
        for (const phrase of [...words.all, ...words.other, ...words.foreign, ...words.specific]) {
            if (!isAscii(phrase)) {
                console.log(`not ascii: "${phrase}" [${stringUtils_1.charsToCodes(phrase).join(', ')}]`);
                failed++;
            }
        }
        console.log('failed: ', failed);
    })();
}
function isAscii(text) {
    return /^[\u0020-\u007e]+$/i.test(text);
}
exports.isAscii = isAscii;
const unicode = createBadWords(false);
const ascii = createBadWords(true);
function tryRegex(value, flags) {
    try {
        return new RegExp(value, flags);
    }
    catch (e) {
        console.error(e.message);
        return new RegExp(/(?!.*)/);
    }
}
const replaceRegex = (values) => tryRegex(`\\b(?:${values.join('|')})\\b`, 'ugi');
const replaceRegexRU = (values) => tryRegex(`${wordStartRU}(?:${values.join('|')})${wordEndRU}`, 'ugi');
const replaceRegexOther = (values) => tryRegex(`(?:${values.join('|')})`, 'ugi');
const replaceRegexSpecific = (values) => tryRegex(`(?:${values.join('|')})`, 'ug');
const testRegex = (values) => tryRegex(`\\b(?:${values.join('|')})\\b`, 'ui');
const testRegexRU = (values) => tryRegex(`${wordStartRU}(?:${values.join('|')})${wordEndRU}`, 'ui');
const testRegexOther = (values) => tryRegex(`(?:${values.join('|')})`, 'ui');
const testRegexSpecific = (values) => tryRegex(`(?:${values.join('|')})`, 'u');
const regexReplace = replaceRegex(unicode.all);
const regexReplaceRU = replaceRegexRU(unicode.foreign);
const regexReplaceOther = replaceRegexOther(unicode.other);
const regexReplaceSpecific = replaceRegexSpecific(unicode.specific);
const regexReplaceFast = replaceRegex(ascii.all);
const regexReplaceRUFast = replaceRegexRU(ascii.foreign);
const regexReplaceOtherFast = replaceRegexOther(ascii.other);
const regexReplaceSpecificFast = replaceRegexSpecific(ascii.specific);
const regexTest = testRegex(unicode.all);
const regexTestRU = testRegexRU(unicode.foreign);
const regexTestOther = testRegexOther(unicode.other);
const regexTestSpecific = testRegexSpecific(unicode.specific);
const regexTestFast = testRegex(ascii.all);
const regexTestRUFast = testRegexRU(ascii.foreign);
const regexTestOtherFast = testRegexOther(ascii.other);
const regexTestSpecificFast = testRegexSpecific(ascii.specific);
const regexTestFuck = testRegex(unicode.fuck);
const regexReplaceRUSingle = tryRegex(`${unicode.foreign.join('|')}`, 'ugi');
const regexReplacePartial = tryRegex(`${[
    ...unicode.all, ...unicode.foreign, ...unicode.other, ...unicode.specific
].join('|')}`, 'ugi');
const defaultReplacer = match => lodash_1.repeat('*', match.length);
const createReplacerRU = (replacer = defaultReplacer) => match => match.replace(regexReplaceRUSingle, replacer);
function canUseFast(text) {
    return isAscii(text);
}
function slowReplace(text, replacer, replacerRU) {
    return text
        .replace(regexReplace, replacer)
        .replace(regexReplaceRU, replacerRU)
        .replace(regexReplaceOther, replacer)
        .replace(regexReplaceSpecific, replacer);
}
function fastReplace(text, replacer, replacerRU) {
    return text
        .replace(regexReplaceFast, replacer)
        .replace(regexReplaceRUFast, replacerRU)
        .replace(regexReplaceOtherFast, replacer)
        .replace(regexReplaceSpecificFast, replacer);
}
function createFilter(replacer = defaultReplacer) {
    const replacerRU = createReplacerRU(replacer);
    return (text) => canUseFast(text) ?
        fastReplace(text, replacer, replacerRU) :
        slowReplace(text, replacer, replacerRU);
}
exports.createFilter = createFilter;
function slowTest(text) {
    return regexTest.test(text) ||
        regexTestRU.test(text) ||
        regexTestOther.test(text) ||
        regexTestSpecific.test(text);
}
function fastTest(text) {
    return regexTestFast.test(text) ||
        regexTestRUFast.test(text) ||
        regexTestOtherFast.test(text) ||
        regexTestSpecificFast.test(text);
}
function hasBadWords(text) {
    return canUseFast(text) ? fastTest(text) : slowTest(text);
}
exports.hasBadWords = hasBadWords;
function hasFuck(text) {
    return regexTestFuck.test(text);
}
exports.hasFuck = hasFuck;
exports.filterBadWords = createFilter();
function filterName(name) {
    const filtered = exports.filterBadWords(name);
    return name === filtered ? name : lodash_1.repeat('*', name.length);
}
exports.filterName = filterName;
function filterBadWordsPartial(text, replacer = defaultReplacer) {
    return text.replace(regexReplacePartial, replacer);
}
exports.filterBadWordsPartial = filterBadWordsPartial;
function findMatch(text) {
    return unicode.all.find(x => (tryRegex(`\\b(?:${x})\\b`, 'ui')).test(text))
        || unicode.foreign.find(x => (tryRegex(`${wordStartRU}(?:${x})${wordEndRU}`, 'ui')).test(text))
        || unicode.other.find(x => (tryRegex(`${x}`, 'u')).test(text))
        || unicode.specific.find(x => (tryRegex(`${x}`, 'u')).test(text));
}
exports.findMatch = findMatch;
function createMatchEntries() {
    return [
        ...unicode.all.map(line => ({ line, regex: tryRegex(`\\b(?:${line})\\b`, 'ui') })),
        ...unicode.foreign.map(line => ({ line, regex: tryRegex(`${wordStartRU}(?:${line})${wordEndRU}`, 'ui') })),
        ...unicode.other.map(line => ({ line, regex: tryRegex(line, 'ui') })),
        ...unicode.specific.map(line => ({ line, regex: tryRegex(line, 'u') })),
    ];
}
exports.createMatchEntries = createMatchEntries;
//# sourceMappingURL=swears.js.map